## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [13]:
#importing numpy
import numpy as np
from numpy import pi


vector_1= np.arange(5,11)
vector_2= np.arange(15,21)

#inner/outer products w/o numpy 
p_in = [] # initialize empty list

# test to make sure that the two lists are the same length 
assert (len(vector_1)==len(vector_2))

for i in range(len(vector_1)): # iterate through indicies of vectors
    p_in.append(vector_1[i]*vector_2[i])
    
print('Inner Product: %d' %sum(p_in)) # Print Output

# outer product
p_out = [] # initialize empty list

for i in range(len(vector_1)): # iterate through indicies of vectors
    row = [] # initialize sub list
    for j in range(len(vector_2)):
        row.append(vector_1[i]*vector_2[j])
        
    p_out.append(row)

print('Outer Product:') # Print Output
p_out

#outer product with numpy 

n_out = np.outer(vector_1,vector_2)

print('Outer Product:')
n_out


Inner Product: 805
Outer Product:
Outer Product:


array([[ 75,  80,  85,  90,  95, 100],
       [ 90,  96, 102, 108, 114, 120],
       [105, 112, 119, 126, 133, 140],
       [120, 128, 136, 144, 152, 160],
       [135, 144, 153, 162, 171, 180],
       [150, 160, 170, 180, 190, 200]])

### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [40]:
#generate two matrices of random numbers
a= np.random.rand(1,12).reshape(4,3)
b= np.random.rand(1,12).reshape(3,4)


#multiply via for loop
result = [] # final result
for i in range(len(a)):

    row = [] 
    for j in range(len(b)):
        product = 0 
        for v in range(len(a[i])):
            product += a[i][v] * b[v][j]
        row.append(product) 
    result.append(row) 
    
print(result)

#multiply via list comprehension 


#multiply via numpy
c=np.dot(a,b)
print('matrix multiplication via numpy')
print(c)

[[0.9714241515327748, 0.6971852219842397, 0.7218350804612559], [1.1541345447161622, 0.6829834646563078, 0.7374221095724924], [0.5748085963843398, 0.28513334049836975, 0.17989515228299607], [0.7675005791851769, 0.37863036800232247, 0.28756509517435763]]
matrix multiplication via numpy
[[0.97142415 0.69718522 0.72183508 1.02817413]
 [1.15413454 0.68298346 0.73742211 1.25119096]
 [0.5748086  0.28513334 0.17989515 0.55755462]
 [0.76750058 0.37863037 0.2875651  0.77146601]]
